# Generated by Django 5.0.4 on 2024-06-10 20:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=75)),
                ('prenom', models.CharField(max_length=75)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=75)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=75)),
                ('nom', models.CharField(max_length=75)),
                ('prenom', models.CharField(max_length=75)),
                ('mail', models.EmailField(max_length=75)),
                ('motdepasse', models.CharField(max_length=75)),
                ('type', models.CharField(choices=[('AMATEUR', 'Amateur'), ('PROFESSIONNEL', 'Professionnel')], default='AMATEUR', max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=75)),
                ('annee', models.DateField()),
                ('realisateur', models.CharField(max_length=75)),
                ('affiche', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('acteur', models.ManyToManyField(related_name='film', to='filmographie.acteur')),
                ('categorie', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='filmographie.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(help_text='La note doit être un entier entre 0 et 20.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('commentaire', models.TextField(null=True)),
                ('date', models.DateField()),
                ('film', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='filmographie.film')),
                ('utilisateur', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='filmographie.utilisateur')),
            ],
        ),
    ]
