# Generated by Django 5.0.6 on 2024-06-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monappli', '0008_alter_capteurs_nom2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capteurs',
            name='nom2',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
