# Generated by Django 5.0.4 on 2024-06-20 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monappli', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donnees',
            name='capteur',
        ),
        migrations.AddField(
            model_name='donnees',
            name='capteurID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monappli.capteurs'),
        ),
        migrations.AlterField(
            model_name='capteurs',
            name='emplacement',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='capteurs',
            name='nom',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='capteurs',
            name='piece',
            field=models.CharField(max_length=255),
        ),
    ]
