# Generated by Django 5.0.6 on 2024-06-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monappli', '0004_alter_capteurs_emplacement_alter_capteurs_nom2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capteurs',
            name='nom2',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
