# Generated by Django 5.0.6 on 2024-06-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monappli', '0002_remove_donnees_capteur_donnees_capteurid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capteurs',
            name='nom2',
            field=models.CharField(default='default_value', max_length=255),
            preserve_default=False,
        ),
    ]
